//! Generated SDK client adapter — bridges AppContext to the co-generated SDK.
//!
//! Auto-generated by @fern-api/cli-generator. Do not edit by hand.

#![allow(dead_code)]

use std::future::Future;
use std::pin::Pin;
use std::sync::Arc;

use fern_cli_sdk::error::CliError;
use fern_cli_sdk::openapi::AppContext;
use fern_cli_sdk::sdk_executor::{CliExecutor, SdkError, SdkRequestExecutor};

// ---------------------------------------------------------------------------
// Executor adapter: CliExecutor → SDK RequestExecutor
// ---------------------------------------------------------------------------

struct CliExecutorAdapter(Arc<CliExecutor>);

impl agentmail_sdk::RequestExecutor for CliExecutorAdapter {
    fn execute(
        &self,
        request: reqwest::Request,
    ) -> Pin<
        Box<
            dyn Future<Output = Result<reqwest::Response, Box<dyn std::error::Error + Send + Sync>>>
                + Send
                + '_,
        >,
    > {
        Box::pin(async move {
            SdkRequestExecutor::execute(&*self.0, request)
                .await
                .map_err(|e| Box::new(e) as Box<dyn std::error::Error + Send + Sync>)
        })
    }
}

// ---------------------------------------------------------------------------
// client — construct a fully-wired SDK root client
// ---------------------------------------------------------------------------

/// Build the SDK root client from the CLI's runtime context.
///
/// The returned client routes all HTTP through the CLI's executor, so
/// it inherits auth, retries, TLS, and global headers automatically.
pub fn client(ctx: &AppContext) -> agentmail_sdk::api::ApiClient {
    let executor = ctx.build_sdk_executor();
    let adapter = Arc::new(CliExecutorAdapter(executor));
    // Seed the base URL from the CLI's own resolution (--base-url / env >
    // spec base_url > server root). `ClientConfig::default()` carries an
    // empty `base_url` for any API that declares no environment, which made
    // every custom command fail on a relative URL before the executor ran.
    let config = agentmail_sdk::ClientConfig {
        base_url: ctx.effective_base_url(),
        ..Default::default()
    };
    let http_client = agentmail_sdk::HttpClient::with_executor(
        adapter as Arc<dyn agentmail_sdk::RequestExecutor>,
        config.clone(),
    );
    agentmail_sdk::api::ApiClient {
        config,
        inboxes: agentmail_sdk::api::InboxesClient {
            http_client: http_client.clone(),
            api_keys: agentmail_sdk::api::resources::inboxes::ApiKeysClient2 { http_client: http_client.clone() },
            drafts: agentmail_sdk::api::resources::inboxes::DraftsClient2 { http_client: http_client.clone() },
            events: agentmail_sdk::api::resources::inboxes::EventsClient { http_client: http_client.clone() },
            lists: agentmail_sdk::api::resources::inboxes::ListsClient2 { http_client: http_client.clone() },
            messages: agentmail_sdk::api::resources::inboxes::MessagesClient { http_client: http_client.clone() },
            metrics: agentmail_sdk::api::resources::inboxes::MetricsClient2 { http_client: http_client.clone() },
            threads: agentmail_sdk::api::resources::inboxes::ThreadsClient2 { http_client: http_client.clone() },
            webhooks: agentmail_sdk::api::resources::inboxes::WebhooksClient2 { http_client: http_client.clone() },
        },
        pods: agentmail_sdk::api::PodsClient {
            http_client: http_client.clone(),
            api_keys: agentmail_sdk::api::resources::pods::ApiKeysClient3 { http_client: http_client.clone() },
            domains: agentmail_sdk::api::resources::pods::DomainsClient2 { http_client: http_client.clone() },
            drafts: agentmail_sdk::api::resources::pods::DraftsClient3 { http_client: http_client.clone() },
            inboxes: agentmail_sdk::api::resources::pods::InboxesClient2 { http_client: http_client.clone() },
            lists: agentmail_sdk::api::resources::pods::ListsClient3 { http_client: http_client.clone() },
            metrics: agentmail_sdk::api::resources::pods::MetricsClient3 { http_client: http_client.clone() },
            threads: agentmail_sdk::api::resources::pods::ThreadsClient3 { http_client: http_client.clone() },
            webhooks: agentmail_sdk::api::resources::pods::WebhooksClient3 { http_client: http_client.clone() },
        },
        webhooks: agentmail_sdk::api::WebhooksClient { http_client: http_client.clone() },
        agent: agentmail_sdk::api::AgentClient { http_client: http_client.clone() },
        api_keys: agentmail_sdk::api::ApiKeysClient { http_client: http_client.clone() },
        auth: agentmail_sdk::api::AuthClient { http_client: http_client.clone() },
        domains: agentmail_sdk::api::DomainsClient { http_client: http_client.clone() },
        drafts: agentmail_sdk::api::DraftsClient { http_client: http_client.clone() },
        lists: agentmail_sdk::api::ListsClient { http_client: http_client.clone() },
        metrics: agentmail_sdk::api::MetricsClient { http_client: http_client.clone() },
        organizations: agentmail_sdk::api::OrganizationsClient { http_client: http_client.clone() },
        threads: agentmail_sdk::api::ThreadsClient { http_client: http_client.clone() },
    }
}

// ---------------------------------------------------------------------------
// block_on — async SDK call → sync handler result
// ---------------------------------------------------------------------------

/// Execute an async SDK operation from a synchronous custom-command handler.
///
/// Bridges the SDK's `ApiError` into the CLI's `CliError` so `?` works
/// naturally in handler bodies.
pub fn block_on<F, T>(future: F) -> Result<T, CliError>
where
    F: Future<Output = Result<T, agentmail_sdk::ApiError>>,
{
    tokio::task::block_in_place(|| {
        let handle = tokio::runtime::Handle::current();
        handle.block_on(future).map_err(convert_api_error)
    })
}

fn convert_api_error(e: agentmail_sdk::ApiError) -> CliError {
    match e {
        agentmail_sdk::ApiError::Http { status, message } => {
            fern_cli_sdk::error::api_error_from_body(status, &message)
        }
        agentmail_sdk::ApiError::Network(err) => {
            CliError::Other(anyhow::anyhow!("SDK network error: {err}"))
        }
        agentmail_sdk::ApiError::Executor(boxed) => match boxed.downcast::<SdkError>() {
            Ok(sdk_error) => sdk_error.into_cli_error(),
            Err(other) => CliError::Other(anyhow::anyhow!("SDK executor error: {other}")),
        },
        other => CliError::Other(anyhow::anyhow!("SDK error: {other}")),
    }
}
